stages:
  - test
  - build
  - deploy

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/SAST-IaC.latest.gitlab-ci.yml

docker-build:
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" $REGISTRY
  script:
    - docker build --pull -t "$REGISTRY/websites/ping_thats_a_nice_argument_unfortunately_com-website" .
    - docker push "$REGISTRY/websites/ping_thats_a_nice_argument_unfortunately_com-website"
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

deploy-job:
  stage: deploy
  before_script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" $REGISTRY
  script:
    - docker-compose -f 'docker-compose.yml' --project-name 'w-ptnaudc' down
    - docker-compose -f 'docker-compose.yml' --project-name 'w-ptnaudc' up -d
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - docker-compose.yml
