version: "3"

services:
  web:
    image: registry.vapronva.pw/websites/ping_thats_a_nice_argument_unfortunately_com-website:latest
    restart: unless-stopped
    container_name: "web-ping_thats_a_nice_argument_unfortunately_com"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - VIRTUAL_HOST=ping.thats-a-nice-argument-unfortunately.com
      - VIRTUAL_PORT=8000
    networks:
      - "w-ptnaudc-network"

networks:
  w-ptnaudc-network:
    external: true
